FROM rust as builder

RUN apt-get update && apt-get install -y protobuf-compiler

WORKDIR /
COPY api api
COPY rust rust

WORKDIR rust
RUN cargo build --release -p survey-tool-server

FROM debian:stable-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /rust/target/release/survey-tool-server /app/survey_tool_server

EXPOSE 1504
ENTRYPOINT ["/app/survey_tool_server"]
