[package]
name = "survey-tool-api-client"
description = "Client lib to easy usage of the survey tool api and connect to a survey tool server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = ["grpc"]
grpc = []
rest = []

[dependencies]
tonic = { workspace = true, features = ["channel"] }
tonic-prost = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
base64 = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
