[package]
name = "survey-api-client"
version = "0.1.0"
edition = "2024"

[features]
default = ["grpc"]
grpc = []
rest = []

[dependencies]
tonic = { version = "0.14", default-features = false, features = ["transport", "channel", "codegen", "tls-native-roots"] }
tonic-prost = "0.14"
prost = "0.14"
prost-types = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
